"""empty message

Revision ID: 548af35d5a72
Revises: 1a0eb852c33e
Create Date: 2022-05-26 23:53:00.710596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548af35d5a72'
down_revision = '1a0eb852c33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.String(length=120), nullable=False))
    op.alter_column('genre', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('musicgenre', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.alter_column('musicgenre', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('musicgenre_artist_id_fkey', 'musicgenre', type_='foreignkey')
    op.create_foreign_key(None, 'musicgenre', 'venue', ['venue_id'], ['id'])
    op.drop_column('musicgenre', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musicgenre', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'musicgenre', type_='foreignkey')
    op.create_foreign_key('musicgenre_artist_id_fkey', 'musicgenre', 'artist', ['artist_id'], ['id'])
    op.alter_column('musicgenre', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('musicgenre', 'venue_id')
    op.alter_column('genre', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###
