"""empty message

Revision ID: 9f65704b83c4
Revises: bb45b30d57d3
Create Date: 2022-05-27 01:13:04.444311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f65704b83c4'
down_revision = 'bb45b30d57d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('genre', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('musicgenre', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('musicgenre', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('musicgenre', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('musicgenre', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('genre', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
