"""empty message

Revision ID: ac70b7ea3514
Revises: 9f65704b83c4
Create Date: 2022-05-27 19:09:54.974049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac70b7ea3514'
down_revision = '9f65704b83c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'website', nullable=False, new_column_name='website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'website_link', nullable=False, new_column_name='website')
    # ### end Alembic commands ###
