"""empty message

Revision ID: bb45b30d57d3
Revises: 548af35d5a72
Create Date: 2022-05-27 00:03:09.134420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb45b30d57d3'
down_revision = '548af35d5a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('genre', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('musicgenre', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.alter_column('musicgenre', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('musicgenre_artist_id_fkey', 'musicgenre', type_='foreignkey')
    op.create_foreign_key(None, 'musicgenre', 'venue', ['venue_id'], ['id'])
    op.drop_column('musicgenre', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musicgenre', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'musicgenre', type_='foreignkey')
    op.create_foreign_key('musicgenre_artist_id_fkey', 'musicgenre', 'artist', ['artist_id'], ['id'])
    op.alter_column('musicgenre', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('musicgenre', 'venue_id')
    op.alter_column('genre', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
